### ISSUE TITLE
Error: IncompleteSignatureException

### ISSUE THREAD

**Issue by willfarrell** [fiunchinho/ansible-aws-elasticsearch-module#8]
I'm using `echo -e "{{ec2_access_key}}\n{{ec2_secret_key}}\n{{aws_region}}\njson\n" | aws --profile aws.sandbox configure` to create the profile. Should I be using a different method?

```bash
ansible 2.2.1.0
aws-cli/1.11.49 Python/2.7.13 Darwin/16.4.0 botocore/1.5.12
```

**main.yml**
```yml
---

- name: "Create ElasticSearch cluster"
  ec2_elasticsearch:
    name: "elastic-cloud"
    elasticsearch_version: "5.1"
    region: "{{aws_region}}"
    instance_type: "m3.medium.elasticsearch"
    instance_count: 1
    dedicated_master: False
    #dedicated_master_instance_type: "t2.micro.elasticsearch"
    #dedicated_master_instance_count: 2
    zone_awareness: False
    ebs: False
    volume_type: "standard"
    volume_size: 10
    snapshot_hour: 0
    access_policies: "{{ lookup('file', 'access_policy.json') | from_json }}"
    profile: "aws.sandbox"
  register: response
```

**AWS IAM Profile Policy:**
 AmazonRDSFullAccess
 AmazonEC2FullAccess
 IAMFullAccess
 AmazonElastiCacheFullAccess
 AmazonS3FullAccess
 AWSElasticBeanstalkFullAccess
 AmazonVPCFullAccess
 AmazonRoute53FullAccess
